#Explore Errors

#Create a NameError
#nameerrors value is not referenced before being called

def createNameError():
	return nameerrors

#Create a TypeError
#Cannot add int and str together beacause they are different types
def createTypeError():
	a = 5
	b = "you"
	return a + b






# createNameError()
createTypeError()